# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

fastlane_version "2.80.0"

default_platform(:ios)

platform :ios do
  ENV["XCODE_SCHEME"]="dashwallet"
  ENV["XCODE_PROJECT"]="DashWallet.xcodeproj"
  ENV["XCODE_WORKSPACE"]="DashWallet.xcworkspace"

  desc "Push a new beta build to TestFlight"
  lane :beta do
    ensure_git_status_clean

    cocoapods_install

    increment_build_number

    build_app(
      scheme: ENV["XCODE_SCHEME"],
      configuration: "Release",
      clean: true,
      export_method: "app-store"
    )

    upload_to_testflight(
      skip_submission: true,
      skip_waiting_for_build_processing: true
    )

    # Make sure our directory is clean, except for changes Fastlane has made
    clean_build_artifacts
  end

  desc "Run tests"
  lane :test do
    setup_travis
    
    scan(
      workspace: ENV["XCODE_WORKSPACE"],
      clean: true,
      scheme: ENV["XCODE_SCHEME"],
      devices: ["iPhone 8"],
    )
  end

  private_lane :cocoapods_install do
    cocoapods(
      repo_update: true
    )
  end

end
