#!/bin/bash
set -e

echo "Preparing DAPI-GRPC caches..."

# Both Release and External caches need to be prepared
RELEASE_CACHE="/Users/ross/Library/Caches/CocoaPods/Pods/Release/DAPI-GRPC/0.22.0-dev.8-138d6"
EXTERNAL_CACHE="/Users/ross/Library/Caches/CocoaPods/Pods/External/DAPI-GRPC/ae038979d78df092469bb9b083b1f2f4-138d6"

for DAPI_CACHE in "$RELEASE_CACHE" "$EXTERNAL_CACHE"; do
    if [ -d "$DAPI_CACHE" ]; then
        echo "Preparing $DAPI_CACHE..."
        cd "$DAPI_CACHE"

        # Ensure platform submodule has files
        if [ ! -f "platform/packages/dapi-grpc/protos/core/v0/core.proto" ]; then
            echo "  Initializing platform submodule..."
            git init 2>/dev/null || true
            git submodule update --init --recursive 2>/dev/null || true
            cd platform && git reset --hard 2>/dev/null && cd .. || true
        fi

        # Run pod install for dapi-grpc-pod-installer if needed
        if [ ! -d "dapi-grpc-pod-installer/Pods/!ProtoCompiler" ]; then
            echo "  Installing dapi-grpc-pod-installer pods..."
            pushd dapi-grpc-pod-installer >/dev/null
            pod install --quiet
            popd >/dev/null
        fi

        # Generate proto files if they don't exist
        if [ ! -f "dapi-grpc-pod-installer/Pods/DAPI-GRPC/Core.pbobjc.h" ]; then
            echo "  Generating proto files..."
            mkdir -p dapi-grpc-pod-installer/Pods/DAPI-GRPC

            # Generate core.proto
            dapi-grpc-pod-installer/Pods/!ProtoCompiler/protoc \
                --plugin=protoc-gen-grpc=dapi-grpc-pod-installer/Pods/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin \
                --objc_out=dapi-grpc-pod-installer/Pods/DAPI-GRPC \
                --grpc_out=dapi-grpc-pod-installer/Pods/DAPI-GRPC \
                -I platform/packages/dapi-grpc/protos/core/v0 \
                -I dapi-grpc-pod-installer/Pods/!ProtoCompiler \
                platform/packages/dapi-grpc/protos/core/v0/core.proto 2>&1 | grep -v "^$" || true

            # Generate platform.proto
            dapi-grpc-pod-installer/Pods/!ProtoCompiler/protoc \
                --experimental_allow_proto3_optional \
                --plugin=protoc-gen-grpc=dapi-grpc-pod-installer/Pods/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin \
                --objc_out=dapi-grpc-pod-installer/Pods/DAPI-GRPC \
                --grpc_out=dapi-grpc-pod-installer/Pods/DAPI-GRPC \
                -I platform/packages/dapi-grpc/protos/platform/v0 \
                -I dapi-grpc-pod-installer/Pods/!ProtoCompiler \
                platform/packages/dapi-grpc/protos/platform/v0/platform.proto 2>&1 | grep -v "^$" || true

            echo "  ✓ Proto files generated"
        else
            echo "  ✓ Proto files already exist"
        fi

        # Modify podspec to skip prepare_command
        if grep -q "git submodule update" DAPI-GRPC.podspec 2>/dev/null; then
            echo "  Updating podspec to skip prepare_command..."
            cat > DAPI-GRPC.podspec.new << 'PODSPEC_EOF'
Pod::Spec.new do |s|
  s.name     = "DAPI-GRPC"
  s.version  = "0.22.0-dev.8"
  s.license  = "MIT"
  s.authors  = { 'Dash Core Group, Inc.' => 'contact@dash.org' }
  s.homepage = "https://github.com/dashevo/platform/tree/master/packages/dapi-grpc"
  s.summary = "Dash's Decentralized API GRPC"
  s.source = { :git => 'https://github.com/dashevo/dashsync-iOS.git', :tag => 'dapi-0.22.0-dev.8' }

  s.ios.deployment_target = "13.0"
  s.osx.deployment_target = "10.15"

  # Base directory where the .proto files are.
  src = "platform/packages/dapi-grpc/protos"

  # Run protoc with the Objective-C and gRPC plugins to generate protocol messages and gRPC clients.
  s.dependency "!ProtoCompiler-gRPCPlugin", "~> 1.0"

  # Pods directory corresponding to this app's Podfile, relative to the location of this podspec.
  pods_root = 'dapi-grpc-pod-installer/Pods'

  # Path where Cocoapods downloads protoc and the gRPC plugin.
  protoc_dir = "#{pods_root}/!ProtoCompiler"
  protoc = "#{protoc_dir}/protoc"
  plugin = "#{pods_root}/!ProtoCompiler-gRPCPlugin/grpc_objective_c_plugin"

  # Directory where the generated files will be placed.
  dir = "#{pods_root}/#{s.name}"

  s.prepare_command = <<-CMD
    echo "Proto files already generated, skipping prepare_command"
  CMD

  # Files generated by protoc
  s.subspec "Messages" do |ms|
    ms.source_files = "#{dir}/*.pbobjc.{h,m}", "#{dir}/**/*.pbobjc.{h,m}"
    ms.header_mappings_dir = dir
    ms.requires_arc = false
    # The generated files depend on the protobuf runtime.
    ms.dependency "Protobuf"
  end

  # Files generated by the gRPC plugin
  s.subspec "Services" do |ss|
    ss.source_files = "#{dir}/*.pbrpc.{h,m}", "#{dir}/**/*.pbrpc.{h,m}"
    ss.header_mappings_dir = dir
    ss.requires_arc = true
    # The generated files depend on the gRPC runtime, and on the files generated by protoc.
    ss.dependency "gRPC-ProtoRPC"
    ss.dependency "#{s.name}/Messages"
  end

  s.pod_target_xcconfig = {
    # This is needed by all pods that depend on Protobuf:
    'GCC_PREPROCESSOR_DEFINITIONS' => '$(inherited) GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS=1',
    # This is needed by all pods that depend on gRPC-RxLibrary:
    'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
  }
end
PODSPEC_EOF
            mv DAPI-GRPC.podspec.new DAPI-GRPC.podspec
            echo "  ✓ Podspec updated"
        fi
    fi
done

echo "✓ DAPI-GRPC preparation complete"
